#!/bin/bash

# 1. Lokasi Project (Backend)
PROJECT_DIR="/home/aen/hybrid-cli-storage/app/backend"

# 2. Lokasi Python KHUSUS milik project ini
# Ini akan memaksa script memakai library yang benar, meski kamu sedang di environment lain
VENV_PYTHON="/home/aen/hybrid-cli-storage/venv/bin/python"

# 3. Masuk ke folder project
cd "$PROJECT_DIR"

# 4. Jalankan script menggunakan Python khusus tadi
"$VENV_PYTHON" cli_storage.py "$@"
